import { dana } from "@/utils/local_fonts";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import LayoutIndex from "@/app/components/layouts/LayoutIndex";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dana.variable} font-sans bg-neutral-50`}>
        <LayoutIndex>
          {children}
        </LayoutIndex>
      </body>
    </html>
  );
}
